"""Refresh the live lab's deployment files inside this repo. Never pushes.

    python -m demo.build_deploy                         # demo_assets/ + demo/requirements.txt
    python -m demo.build_deploy --weights-out <dir>     # also stage the HF weights folder

Streamlit Community Cloud runs `demo/app.py` straight from this repo. It has
no raw data, so this writes what the app needs in deployed mode:

    demo_assets/{tiles,masks,preds/<arm>}/ + manifest.json
        curated tiles, 0/1 masks, seed-42 0/1 prediction masks and the
        Hugging Face repo the app downloads checkpoints from
    demo/requirements.txt
        slim CPU requirements; Community Cloud reads it before the root
        environment.yml because it sits next to the entrypoint

`--weights-out` stages the four seed-42 checkpoints and a model card for the
Hugging Face model repo, in an empty folder outside this repo.
Needs the local raw tiles, masks and results_v2 checkpoints.
"""

from __future__ import annotations

import argparse
import json
import shutil
import urllib.request
from importlib.metadata import version
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
from PIL import Image

from demo import data, inference
from src.utils.paths import Config, project_root

DEFAULT_WEIGHTS_REPO = "Yaser-Alharbi/vessel-stain-lab-weights"
REQUIREMENTS_PATH = Path(__file__).resolve().parent / "requirements.txt"
TORCH_INDEX = "https://download.pytorch.org/whl/cpu"
PYTHONS = ("3.11", "3.12", "3.13")


def select_tiles(cube: data.Cube, per_sort: int) -> Dict[str, List[str]]:
    """Top `per_sort` tiles for each ranking (except 'Tile id'), deduplicated."""
    picked: Dict[str, List[str]] = {}
    for sort in data.SORTS[:-1]:
        for tile_id in data.rank_tiles(cube, sort)[:per_sort]:
            picked.setdefault(tile_id, []).append(sort)
    return picked


def _save_mask(mask: np.ndarray, path: Path) -> None:
    """Write a 0/1 uint8 mask as PNG."""
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(mask.astype(np.uint8)).save(path, optimize=True)


def _wheel_url(package: str, ver: str, py: str) -> str:
    """PyTorch CPU wheel URL for one package, version and CPython version."""
    tag = "cp" + py.replace(".", "")
    return f"{TORCH_INDEX}/{package}-{ver}%2Bcpu-{tag}-{tag}-manylinux_2_28_x86_64.whl"


def _check_url(url: str) -> None:
    """HEAD the URL; raise if it does not resolve."""
    req = urllib.request.Request(url, method="HEAD")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            if resp.status != 200:
                raise RuntimeError(f"{url} -> HTTP {resp.status}")
    except OSError as exc:
        raise RuntimeError(f"wheel URL does not resolve: {url} ({exc})") from exc


def _requirements() -> str:
    """Community Cloud requirements.

    torch/torchvision come as direct CPU wheel URLs, one per Python version
    (markers), so uv never consults the PyTorch index for other packages and a
    forced Python upgrade still installs. Everything else is pinned to this env.
    """
    lines = ["# Generated by `python -m demo.build_deploy`; do not edit by hand."]
    for package in ("torch", "torchvision"):
        ver = version(package).split("+")[0]
        for py in PYTHONS:
            url = _wheel_url(package, ver, py)
            _check_url(url)
            lines.append(f'{package} @ {url} ; python_version == "{py}"')
    lines += [
        f"segmentation-models-pytorch=={version('segmentation-models-pytorch')}",
        f"timm=={version('timm')}",
        f"albumentations=={version('albumentations')}",
        f"opencv-python-headless=={version('opencv-python')}",
        f"numpy=={version('numpy')}",
        f"PyYAML=={version('PyYAML')}",
        f"Pillow=={version('Pillow')}",
        f"streamlit=={version('streamlit')}",
        f"huggingface_hub=={version('huggingface_hub')}",
    ]
    return "\n".join(lines) + "\n"


def _weights_readme() -> str:
    """Model card for the weights repo."""
    return f"""---
library_name: segmentation-models-pytorch
tags:
- image-segmentation
- histology
---

# Kidney blood-vessel segmentation weights

Four U-Net + ResNet-34 checkpoints (seed {data.LIVE_SEED}), one per stain-augmentation
arm: `rgb_aug`, `hed_only`, `macenko_only`, `full_stain_aware`. Binary
blood-vessel segmentation on 512x512 HuBMAP kidney tiles, sigmoid > 0.5.

Load with `smp.Unet(encoder_name="resnet34", encoder_weights=None, in_channels=3,
classes=1)` and `load_state_dict(torch.load(path))`.

Code, methods and results: {data.REPO_URL}
"""


def _write_text(path: Path, text: str) -> None:
    """Write UTF-8 text, creating parents."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _load_models(cfg: Config, arms: List[str], device) -> Dict[str, Any]:
    """Seed-42 model per arm, loaded from the local checkpoints."""
    models = {}
    for arm in arms:
        ckpt = data.checkpoint_path(cfg, arm, data.LIVE_SEED)
        if ckpt is None:
            raise FileNotFoundError(f"missing seed-{data.LIVE_SEED} checkpoint for {arm}")
        models[arm] = inference.load_model(ckpt, device)
    return models


def _stage_tile(cfg: Config, tile_id: str, models: Dict[str, Any], assets: Path, device) -> None:
    """Write one tile, its mask and every arm's seed-42 prediction mask."""
    img, gt = data.load_tile(cfg, tile_id)
    (assets / "tiles").mkdir(parents=True, exist_ok=True)
    Image.fromarray(img).save(assets / "tiles" / f"{tile_id}.png", optimize=True)
    _save_mask(gt, assets / "masks" / f"{tile_id}.png")
    for arm, model in models.items():
        pred = inference.predict(model, arm, img, device)
        _save_mask(pred, assets / "preds" / arm / f"{tile_id}.png")


def _stage_weights(cfg: Config, arms: List[str], out: Path) -> None:
    """Copy the seed-42 checkpoints and a model card into an empty folder outside the repo."""
    root = project_root()
    if out.resolve().is_relative_to(root):
        raise ValueError(f"--weights-out must be outside the repo ({root})")
    if out.exists() and any(out.iterdir()):
        raise ValueError(f"--weights-out {out} is not empty; pick a new folder")
    out.mkdir(parents=True, exist_ok=True)
    for arm in arms:
        ckpt = data.checkpoint_path(cfg, arm, data.LIVE_SEED)
        shutil.copy2(ckpt, out / ckpt.name)
    _write_text(out / "README.md", _weights_readme())


def build(per_sort: int, weights_repo: str) -> Dict[str, int]:
    """Rewrite demo_assets/ and demo/requirements.txt; return tile counts."""
    cfg = data.load_demo_config()
    if not data.local_mode(cfg):
        raise RuntimeError("raw tiles/masks not found (or DEMO_FORCE_CURATED=1); "
                           "build_deploy needs local data")
    arms = data.arms_from_config(cfg)
    summary = data.load_summary(cfg)
    requirements = _requirements()  # fail early if a wheel URL is missing
    device = inference.resolve_device()
    models = _load_models(cfg, arms, device)

    assets = data.ASSETS_DIR
    if assets.exists():
        shutil.rmtree(assets)  # generated folder: rebuilt from scratch every time
    manifest = {"seed": data.LIVE_SEED, "arms": arms, "weights_repo": weights_repo, "tiles": []}
    for split in ("val", "test"):
        picked = select_tiles(data.build_cube(summary, arms, split), per_sort)
        for tile_id, reasons in picked.items():
            _stage_tile(cfg, tile_id, models, assets, device)
            manifest["tiles"].append({"id": tile_id, "split": split, "reasons": reasons})
    _write_text(assets / "manifest.json", json.dumps(manifest, indent=2))
    _write_text(REQUIREMENTS_PATH, requirements)
    return {f"{s}_tiles": sum(t["split"] == s for t in manifest["tiles"]) for s in ("val", "test")}


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--per-sort", type=int, default=4, help="tiles per ranking per split")
    parser.add_argument("--weights-repo", default=DEFAULT_WEIGHTS_REPO,
                        help="HF model repo id the app downloads checkpoints from")
    parser.add_argument("--weights-out", type=Path,
                        help="also stage the HF weights folder here (empty, outside the repo)")
    args = parser.parse_args()
    counts = build(args.per_sort, args.weights_repo)
    print(f"[build_deploy] wrote {data.ASSETS_DIR} {counts} and {REQUIREMENTS_PATH}")
    if args.weights_out:
        _stage_weights(data.load_demo_config(), data.arms_from_config(data.load_demo_config()),
                       args.weights_out.expanduser())
        print(f"[build_deploy] staged HF weights in {args.weights_out} (not pushed)")
    print("[build_deploy] nothing pushed.")


if __name__ == "__main__":
    main()
